fix: filter online_users in PublicMessage
RyanHsun/simple-twitter-frontend pull request #41
Opened 2021-08-11 09:19 UTC by DaisyChen-TW

新增功能：過濾重複的上線使用者

昨天在後端還沒過濾前
加上filter可以成功過濾，但devtool一直報錯
vue Error in created hook: "TypeError: Cannot read property 'filter' of undefined"

後來又看到下面這篇文，才確認是非同步的關係，所以我在created加上async await
就解決error
https://stackoverflow.com/questions/49663539/why-error-in-render-typeerror-cannot-read-property-filter-of-undefined-ret

2021-08-11 10:38 UTC, DaisyChen-TW commented
後來發現少了await跟error
再新增一個commit
fix: resolve async await in PublicMessage

2021-08-12 19:05 UTC, RyanHsun reviewed
已解決因需要過濾使用者而加上的程式設定，但 console 會持續顯示錯誤的問題。

2021-08-12 19:06 UTC, RyanHsun requested changes
> 後來發現少了await跟error
> 再新增一個commit
> fix: resolve async await in PublicMessage

就如同測試提到的，主要會持續出現錯誤不是非同步的問題，而是放在 created 內的 this.fetchOnlineUsers() 沒放引數給函式的參數 data 接收，所以會在 console 顯示 
`Cannot read property 'filter' of undefined" `

這是執行使用者進入公開聊天室的相關 socket 事件流程：
1. 有使用者進入公開聊天室 
2. 前端會執行 emit 事件 join_public_room，送出使用者 id
2. 後端用 on 接收到 userId 知道該位使用者加入聊天室
3. 後端 emit 事件 online_users 跟 new_join，送出使用者資料
4. 前端再用 on 接收 online_users 跟 new_join 
5. 前端更新資料重新渲染使用者清單

因為 socket 連線已建立所以如果 server 用 emit 發出了事件，放在 sockets : {} 內的語法會持續監聽自動用 on 接收到，所以也就不需要把 this.$socket.on('online_users') 放在 mounted 或 updated 中～

Vue 生命週期有許多種狀態觀念比較複雜～剛剛看到這篇針對理解生命週期做的小 Demo [https://blog.csdn.net/saber04/article/details/96845526]
有空可以像這樣試試～應該就會比較能夠理解整個生命週期

2021-08-12 19:20 UTC, RyanHsun approved these changes
> fix: resolve function parameters undefined problem in PublicMessage, noneed use created just use it in sockets

已解決並更新：程式在執行過濾重複使用者相關語法但 console 會持續顯示 filtter undefined 錯誤的問題。

2021-08-12 19:29 UTC, merged